-- =============================================
-- SUPABASE SQL FOR BOOKINGS TABLE
-- Run this in your Supabase SQL Editor
-- =============================================

-- Step 1: Create the table (if not exists)
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  pickup_location TEXT NOT NULL,
  drop_location TEXT NOT NULL,
  travel_date DATE NOT NULL,
  travel_time TIME NOT NULL,
  car_type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Step 2: Enable RLS
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Step 3: Create INSERT policy (IMPORTANT - allows anonymous inserts)
DROP POLICY IF EXISTS "Allow anyone to insert bookings" ON bookings;
CREATE POLICY "Allow anyone to insert bookings" ON bookings
  FOR INSERT TO anon WITH CHECK (true);

-- Step 4: Create SELECT policy (optional - for viewing bookings)
DROP POLICY IF EXISTS "Allow anyone to view bookings" ON bookings;
CREATE POLICY "Allow anyone to view bookings" ON bookings
  FOR SELECT TO anon USING (true);

